spring:
  application.name: beer-api-consumer-junit5
  
  cloud.stream.bindings.input-in-0.destination: verifications
  
server.port: ${PORT:8081}
logging:
  level:
    org.springframework.cloud: debug